<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Support\Facades\DB;

class Reply extends BaseMode
{
    use HasFactory;

    public function post()
    {
        return $this->belongsTo(Post::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public static function savedCallback()
    {
        return function ($model) {
            // 构建path
            $path = '-' . $model->id . '-';
            if ($model->parent_id != 0) {
                $parent = Reply::find($model->parent_id);
                if ($parent) {
                    $path .= $model->id . '-';
                } else {
                    $path = '';
                }
            }
            DB::table("replies")->where('id', $model->id)->update(['path' => $path]);
            return parent::savedCallback()($model); // TODO: Change the autogenerated stub
        };
    }
}
